I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 50, in script call
    call TiaDeCascais
  File "game/TiaDeCascais.rpy", line 3, in script
    if day == 1:
  File "game/TiaDeCascais.rpy", line 5, in <module>
    elif dia == 2:
NameError: name 'dia' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 50, in script call
    call TiaDeCascais
  File "game/TiaDeCascais.rpy", line 3, in script
    if day == 1:
  File "C:\Users\ASUS\Downloads\renpy-8.0.0-sdk\renpy\ast.py", line 2115, in execute
    if renpy.python.py_eval(condition):
  File "C:\Users\ASUS\Downloads\renpy-8.0.0-sdk\renpy\python.py", line 1092, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\ASUS\Downloads\renpy-8.0.0-sdk\renpy\python.py", line 1085, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/TiaDeCascais.rpy", line 5, in <module>
    elif dia == 2:
NameError: name 'dia' is not defined

Windows-10-10.0.22000 AMD64
Ren'Py 8.0.3.22090809
CozyJam 1.0
Wed Sep 21 10:24:42 2022
